In [1]:
# importing SBopen class from mplsoccer to open the data
from mplsoccer import Sbopen

# The first thing we have to do is open the data. We use a parser SBopen available in mplsoccer.
parser = Sbopen()

In [2]:
# opening data using competition method
df_competition = parser.competition()
# structure of data
df_competition.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42 entries, 0 to 41
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   competition_id             42 non-null     int64
 1   season_id                  42 non-null     int64
 2   country_name               42 non-null     object
 3   competition_name           42 non-null     object
 4   competition_gender         42 non-null     object
 5   competition_youth          42 non-null     bool
 6   competition_international  42 non-null     bool
 7   season_name                42 non-null     object
 8   match_updated              42 non-null     object
 9   match_updated_360          41 non-null     object
 10  match_available_360        3 non-null      object
 11  match_available            42 non-null     object
dtypes: bool(2), int64(2), object(8)
memory usage: 3.5+ KB

In [13]:
# see the different competitions data
df_competition.competition_name.unique()

array(['Champions League', "FA Women's Super League", 'FIFA World Cup',
       'Indian Super league', 'La Liga', 'NWSL', 'Premier League',
       'UEFA Euro', "UEFA Women's Euro", "Women's World Cup"],
      dtype=object)

In [18]:
df_competition[['competition_name', 'competition_id', 'season_id']][df_competition['competition_name'] == 'Premier League']

   competition_name  competition_id  season_id
38   Premier League               2         44

In [19]:
df_match = parser.match(competition_id=2, season_id=44)

In [21]:
df_match.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33 entries, 0 to 32
Data columns (total 48 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   match_id                         33 non-null     int64
 1   match_date                       33 non-null     datetime64[ns]
 2   kick_off                         33 non-null     datetime64[ns]
 3   home_score                       33 non-null     int64
 4   away_score                       33 non-null     int64
 5   match_status                     33 non-null     object
 6   match_status_360                 33 non-null     object
 7   last_updated                     33 non-null     datetime64[ns]
 8   last_updated_360                 33 non-null     datetime64[ns]
 9   match_week                       33 non-null     int64
 10  competition_id                   33 non-null     int64
 11  country_name                     33 non-null     object
 12  competition_name                 33 non-null     object
 13  season_id                        33 non-null     int64
 14  season_name                      33 non-null     object
 15  home_team_id                     33 non-null     int64
 16  home_team_name                   33 non-null     object
 17  home_team_gender                 33 non-null     object
 18  home_team_group                  0 non-null      object
 19  home_team_country_id             33 non-null     int64
 20  home_team_country_name           33 non-null     object
 21  home_team_managers_id            31 non-null     float64
 22  home_team_managers_name          31 non-null     object
 23  home_team_managers_nickname      31 non-null     object
 24  home_team_managers_dob           31 non-null     datetime64[ns]
 25  home_team_managers_country_id    31 non-null     float64
 26  home_team_managers_country_name  31 non-null     object
 27  away_team_id                     33 non-null     int64
 28  away_team_name                   33 non-null     object
 29  away_team_gender                 33 non-null     object
 30  away_team_group                  0 non-null      object
 31  away_team_country_id             33 non-null     int64
 32  away_team_country_name           33 non-null     object
 33  away_team_managers_id            31 non-null     float64
 34  away_team_managers_name          31 non-null     object
 35  away_team_managers_nickname      31 non-null     object
 36  away_team_managers_dob           31 non-null     datetime64[ns]
 37  away_team_managers_country_id    31 non-null     float64
 38  away_team_managers_country_name  31 non-null     object
 39  metadata_data_version            33 non-null     object
 40  metadata_shot_fidelity_version   33 non-null     object
 41  metadata_xy_fidelity_version     33 non-null     object
 42  competition_stage_id             33 non-null     int64
 43  competition_stage_name           33 non-null     object
 44  stadium_id                       33 non-null     int64
 45  stadium_name                     33 non-null     object
 46  stadium_country_id               33 non-null     int64
 47  stadium_country_name             33 non-null     object
dtypes: datetime64[ns](6), float64(4), int64(13), object(25)
memory usage: 12.5+ KB

In [27]:
df_match['home_team_name'].unique()

array(['Wolverhampton Wanderers', 'Arsenal', 'Middlesbrough',
       'Leeds United', 'Liverpool', 'Blackburn Rovers', 'Aston Villa',
       'Manchester United', 'Manchester City', 'Chelsea',
       'Tottenham Hotspur', 'Southampton', 'Birmingham City',
       'Bolton Wanderers', 'Fulham', 'Charlton Athletic',
       'Newcastle United'], dtype=object)

In [29]:
df_match

,match_id,match_date,kick_off,home_score,away_score,match_status,match_status_360,last_updated,last_updated_360,match_week,...,away_team_managers_country_name,metadata_data_version,metadata_shot_fidelity_version,metadata_xy_fidelity_version,competition_stage_id,competition_stage_name,stadium_id,stadium_name,stadium_country_id,stadium_country_name
0,3749052,2004-02-07,2004-02-07 16:00:00,1,3,available,scheduled,2020-07-29 05:00:00.000000,2021-06-13 16:17:31.694,2,...,France,1.1.0,2,2,1,Regular Season,217,Molineux Stadium,68,England
1,3749522,2003-12-26,2003-12-26 13:00:00,3,0,available,scheduled,2020-07-29 05:00:00.000000,2021-06-13 16:17:31.694,18,...,England,1.1.0,2,2,1,Regular Season,1000243,Highbury Stadium,68,England
2,3749246,2004-03-28,2004-03-28 17:05:00,1,1,available,scheduled,2020-07-29 05:00:00.000000,2021-06-13 16:17:31.694,30,...,Scotland,1.1.0,2,2,1,Regular Season,1000243,Highbury Stadium,68,England
3,3749257,2004-05-15,2004-05-15 16:00:00,2,1,available,scheduled,2020-08-30 08:12:14.579037,2021-06-13 16:17:31.694,38,...,England,1.1.0,2,2,1,Regular Season,1000243,Highbury Stadium,68,England
4,3749642,2004-02-28,2004-02-28 16:00:00,2,1,available,scheduled,2020-07-29 05:00:00.000000,2021-06-13 16:17:31.694,27,...,England,1.1.0,2,2,1,Regular Season,1000243,Highbury Stadium,68,England
5,3749358,2003-08-24,2003-08-24 17:05:00,0,4,available,scheduled,2020-07-29 05:00:00.000000,2021-06-13 16:17:31.694,1,...,France,1.1.0,2,2,1,Regular Season,214,Riverside Stadium,68,England
6,3749346,2003-11-01,2003-11-01 16:00:00,1,4,available,scheduled,2020-07-29 05:00:00.000000,2021-06-13 16:17:31.694,1,...,France,1.1.0,2,2,1,Regular Season,213,Elland Road,68,England
7,3749253,2003-10-04,2003-10-04 13:30:00,1,2,available,scheduled,2020-07-29 05:00:00.000000,2021-06-13 16:17:31.694,1,...,NaN,1.1.0,2,2,1,Regular Season,6,Anfield,68,England
8,3749079,2003-10-18,2003-10-18 16:00:00,2,1,available,scheduled,2020-07-29 05:00:00.000000,2021-06-13 16:17:31.694,9,...,Italy,1.1.0,2,2,1,Regular Season,1000243,Highbury Stadium,68,England
9,3749465,2004-03-13,2004-03-13 16:00:00,0,2,available,scheduled,2020-07-29 05:00:00.000000,2021-06-13 16:17:31.694,2,...,France,1.1.0,2,2,1,Regular Season,22,Ewood Park,68,England
10,3749133,2004-01-18,2004-01-18 15:00:00,0,2,available,scheduled,2020-07-29 05:00:00.000000,2021-06-13 16:17:31.694,2,...,France,1.1.0,2,2,1,Regular Season,211,Villa Park,68,England
11,3749528,2003-09-26,2003-09-26 21:00:00,3,2,available,scheduled,2020-07-29 05:00:00.000000,2021-06-13 16:17:31.694,7,...,England,1.1.0,2,2,1,Regular Season,1000243,Highbury Stadium,68,England
12,3749233,2004-02-01,2004-02-01 17:05:00,2,1,available,scheduled,2020-07-29 05:00:00.000000,2021-06-13 16:17:31.694,23,...,England,1.1.0,2,2,1,Regular Season,1000243,Highbury Stadium,68,England
13,3749462,2004-05-01,2004-05-01 13:30:00,0,0,available,scheduled,2020-07-29 05:00:00.000000,2021-06-13 16:17:31.694,35,...,England,1.1.0,2,2,1,Regular Season,1000243,Highbury Stadium,68,England
14,3749552,2003-09-21,2003-09-21 17:05:00,0,0,available,scheduled,2020-07-29 05:00:00.000000,2021-06-13 16:17:31.694,1,...,France,1.1.0,2,2,1,Regular Season,2,Old Trafford,68,England
15,3749296,2003-09-13,2003-09-13 16:00:00,1,1,available,scheduled,2020-07-29 05:00:00.000000,2021-06-13 16:17:31.694,5,...,England,1.1.0,2,2,1,Regular Season,1000243,Highbury Stadium,68,England
16,3749454,2003-08-31,2003-08-31 17:05:00,1,2,available,scheduled,2020-07-29 05:00:00.000000,2021-06-13 16:17:31.694,1,...,France,1.1.0,2,2,1,Regular Season,4715,Etihad Stadium,68,England
17,3749276,2004-02-21,2004-02-21 13:30:00,1,2,available,scheduled,2020-07-29 05:00:00.000000,2021-06-13 16:17:31.694,2,...,France,1.1.0,2,2,1,Regular Season,10,Stamford Bridge,68,England
18,3749068,2004-04-25,2004-04-25 17:05:00,2,2,available,scheduled,2020-07-29 05:00:00.000000,2021-06-13 16:17:31.694,2,...,France,1.1.0,2,2,1,Regular Season,99148,White Hart Lane,68,England
19,3749310,2003-12-29,2003-12-29 21:00:00,0,1,available,scheduled,2020-08-31 20:40:28.969635,2021-06-13 16:17:31.694,1,...,France,1.1.0,2,2,1,Regular Season,4591,St. Mary''s Stadium,68,England
20,3749493,2003-08-16,2003-08-16 16:00:00,2,1,available,scheduled,2020-07-29 05:00:00.000000,2021-06-13 16:17:31.694,1,...,Scotland,1.1.0,2,2,1,Regular Season,1000243,Highbury Stadium,68,England
21,3749434,2003-11-22,2003-11-22 16:00:00,0,3,available,scheduled,2020-07-29 05:00:00.000000,2021-06-13 16:17:31.694,1,...,France,1.1.0,2,2,1,Regular Season,4500,St. Andrews Stadium,68,England
22,3749192,2003-11-30,2003-11-30 15:00:00,0,0,available,scheduled,2020-08-30 07:13:01.092744,2021-06-13 16:17:31.694,14,...,Wales,1.1.0,2,2,1,Regular Season,1000243,Highbury Stadium,68,England
23,3749196,2003-11-08,2003-11-08 16:00:00,2,1,available,scheduled,2020-07-29 05:00:00.000000,2021-06-13 16:17:31.694,12,...,England,1.1.0,2,2,1,Regular Season,1000243,Highbury Stadium,68,England
24,3749448,2004-04-09,2004-04-09 13:30:00,4,2,available,scheduled,2020-07-29 05:00:00.000000,2021-06-13 16:17:31.694,31,...,NaN,1.1.0,2,2,1,Regular Season,1000243,Highbury Stadium,68,England
25,3749360,2003-12-14,2003-12-14 15:00:00,1,0,available,scheduled,2020-07-29 05:00:00.000000,2021-06-13 16:17:31.694,16,...,Scotland,1.1.0,2,2,1,Regular Season,1000243,Highbury Stadium,68,England
26,3749453,2004-04-16,2004-04-16 21:00:00,5,0,available,scheduled,2021-11-14 22:29:00.646120,2021-06-13 16:17:31.694,33,...,Scotland,1.1.0,2,2,1,Regular Season,1000243,Highbury Stadium,68,England
27,3749278,2003-12-20,2003-12-20 16:00:00,1,1,available,scheduled,2020-08-30 07:13:01.092744,2021-06-13 16:17:31.694,1,...,France,1.1.0,2,2,1,Regular Season,4843,University of Bolton Stadium,68,England
28,3749603,2004-05-09,2004-05-09 17:05:00,0,1,available,scheduled,2020-07-29 05:00:00.000000,2021-06-13 16:17:31.694,2,...,France,1.1.0,2,2,1,Regular Season,4844,Loftus Road,68,England
29,3749153,2004-01-10,2004-01-10 16:00:00,4,1,available,scheduled,2020-08-30 08:12:14.579037,2021-06-13 16:17:31.694,21,...,England,1.1.0,2,2,1,Regular Season,1000243,Highbury Stadium,68,England
30,3749403,2004-03-20,2004-03-20 16:00:00,2,1,available,scheduled,2020-07-29 05:00:00.000000,2021-06-13 16:17:31.694,29,...,England,1.1.0,2,2,1,Regular Season,1000243,Highbury Stadium,68,England
31,3749526,2003-10-26,2003-10-26 15:00:00,1,1,available,scheduled,2020-07-29 05:00:00.000000,2021-06-13 16:17:31.694,1,...,France,1.1.0,2,2,1,Regular Season,31,The Valley,68,England
32,3749431,2004-04-11,2004-04-11 17:05:00,0,0,available,scheduled,2020-07-29 05:00:00.000000,2021-06-13 16:17:31.694,2,...,France,1.1.0,2,2,1,Regular Season,4674,St. James'' Park,68,England